# Generated by Django 5.2.1 on 2025-08-18 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodel_dislikes_postmodel_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
