# Generated by Django 5.2.1 on 2025-08-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_postmodel_dislikes_remove_postmodel_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='reaction_type',
        ),
        migrations.AddField(
            model_name='reaction',
            name='value',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10, null=True),
        ),
    ]
